# Generated by Django 3.2.18 on 2023-03-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
